language: go
sudo: false

go:
  - 1.6.x
  - 1.8.x

before_install:
  - go get github.com/mattn/goveralls

install:
  - go get github.com/Masterminds/glide
  - go get github.com/kode4food/go-snapshot
  - go get github.com/jteeuwen/go-bindata/...

script:
  - $GOPATH/bin/glide install
  - $GOPATH/bin/go-snapshot -pkg assets -out assets/assets.go docstring/*.md core/*.lisp -prefix="docstring/" docstring/*.md
  - go test $($GOPATH/bin/glide novendor)
  - $GOPATH/bin/goveralls -service=travis-ci -ignore=assets/assets.go,cli/*.go
